security:
  oauth2:
    resource:
      jwt:
        key-value:
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnXaDQtFEcmUVf2DlcCi1
          V8uPfDT54Z5RG1afpqbAgvor0V3SopLuKEBm8DUGwLume31k9GtUWnm9BjlIWDvK
          Zogn22YyKWWeHVfy+1SHL3owtR4iaS43pVQTEuIBcGC//vCRd8aWByqv0U6zVWoe
          ejG9MiDjyQztUuqi1wJQeDr6Th0m+kAWw7Xk44kd7vp+ZnzAsDJC4S5eS1Dbm8qx
          xHe8C7HxuJAKvafxMjXZmIhocaCSHk/VroDOJYC+a7vl+gNY+qnM1Wr5CYNNkUKw
          mQcrvWJogMeo05eegZBUF//Yhsv4FLDZO0HIvwB3qSKUWwzv4RF922jOYp/3f6Oi
          YwIDAQAB
          -----END PUBLIC KEY-----
    client:
      clientId: employee
      #clientSecret: password@2018
      #accessTokenUri: http://localhost:9001/oauth/token
      #grant-type: client_credentials
      #scope: server

#spring:
#  application:
#    name: maward
#  main:
#    allow-bean-definition-overriding: true
#spring:
#  data:
#    mongodb:
#      host: account-mongodb
#      username: user
#      password: ${MONGODB_PASSWORD}
#      database: sample
#      port: 27017

server:
  port: 6001

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: employee
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: raj
    password: 12345
    driver-class-name: oracle.jdbc.OracleDriver
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS : false
    time-zone: UTC


logging:
  pattern:
    console: '@%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
    file: '@%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
    qa:
      gov:
        customs:
          employee: DEBUG
  file: logs/employee.log
