package qa.gov.customs.training.entity;
// Generated Apr 23, 2019 7:33:17 AM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonBackReference;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;

/**
 * TacCourseOutcome generated by hbm2java
 */
@Entity
@Table(name = "TAC_COURSE_OUTCOME", schema = "CUST_TAC")
public class TacCourseOutcome implements java.io.Serializable {

    private BigDecimal outcomeId;
    private TacCourseMaster tacCourseMaster;
    private String result;

    public TacCourseOutcome() {
    }

    public TacCourseOutcome(BigDecimal outcomeId) {
        this.outcomeId = outcomeId;
    }

    public TacCourseOutcome(BigDecimal outcomeId, TacCourseMaster tacCourseMaster, String result) {
        this.outcomeId = outcomeId;
        this.tacCourseMaster = tacCourseMaster;
        this.result = result;
    }

    @Id

    @Column(name = "OUTCOME_ID", unique = true, nullable = false, precision = 22, scale = 0)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_Sequence")
    @SequenceGenerator(name = "id_Sequence", sequenceName = "TAC_OUTCOME_SEQ", allocationSize = 1)
    public BigDecimal getOutcomeId() {
        return this.outcomeId;
    }

    public void setOutcomeId(BigDecimal outcomeId) {
        this.outcomeId = outcomeId;
    }

    @JsonBackReference(value = "outcomes")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COURSE_ID")
    public TacCourseMaster getTacCourseMaster() {
        return this.tacCourseMaster;
    }

    public void setTacCourseMaster(TacCourseMaster tacCourseMaster) {
        this.tacCourseMaster = tacCourseMaster;
    }
    @NotNull(message = "Expected Results is mandatory")
    @Column(name = "RESULT", length = 2000)
    public String getResult() {
        return this.result;
    }

    public void setResult(String result) {
        this.result = result;
    }

}
