package qa.gov.customs.training.entity;
// Generated Apr 23, 2019 7:33:17 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TacCourseAudience generated by hbm2java
 */
@Entity
@Table(name = "TAC_COURSE_AUDIENCE", schema = "CUST_TAC")
public class TacCourseAudience implements java.io.Serializable {

	private BigDecimal audienceId;
	private TacCourseMaster tacCourseMaster;
	private TacCourseTargetGroup tacCourseTargetGroup;

	public TacCourseAudience() {
	}

	public TacCourseAudience(BigDecimal audienceId) {
		this.audienceId = audienceId;
	}

	public TacCourseAudience(BigDecimal audienceId, TacCourseMaster tacCourseMaster,
			TacCourseTargetGroup tacCourseTargetGroup) {
		this.audienceId = audienceId;
		this.tacCourseMaster = tacCourseMaster;
		this.tacCourseTargetGroup = tacCourseTargetGroup;
	}

	@Id

	@Column(name = "AUDIENCE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_Sequence")
    @SequenceGenerator(name = "id_Sequence", sequenceName = "TAC_AUDIENCE_SEQ")
	public BigDecimal getAudienceId() {
		return this.audienceId;
	}

	public void setAudienceId(BigDecimal audienceId) {
		this.audienceId = audienceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COURSE_ID")
	public TacCourseMaster getTacCourseMaster() {
		return this.tacCourseMaster;
	}

	public void setTacCourseMaster(TacCourseMaster tacCourseMaster) {
		this.tacCourseMaster = tacCourseMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TARGET_ID")
	public TacCourseTargetGroup getTacCourseTargetGroup() {
		return this.tacCourseTargetGroup;
	}

	public void setTacCourseTargetGroup(TacCourseTargetGroup tacCourseTargetGroup) {
		this.tacCourseTargetGroup = tacCourseTargetGroup;
	}

}
