package qa.gov.customs.training.entity;
// Generated Apr 23, 2019 7:33:17 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TacCourseLocation generated by hbm2java
 */
@Entity
@Table(name = "TAC_COURSE_LOCATION", schema = "CUST_TAC")
public class TacCourseLocation implements java.io.Serializable {

	private BigDecimal locationId;
	private String locationName;
	private Set<TacCourseRoom> tacCourseRooms = new HashSet<TacCourseRoom>(0);

	public TacCourseLocation() {
	}

	public TacCourseLocation(BigDecimal locationId) {
		this.locationId = locationId;
	}

	public TacCourseLocation(BigDecimal locationId, String locationName, Set<TacCourseRoom> tacCourseRooms) {
		this.locationId = locationId;
		this.locationName = locationName;
		this.tacCourseRooms = tacCourseRooms;
	}

	@Id

	@Column(name = "LOCATION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_Sequence")
    @SequenceGenerator(name = "id_Sequence", sequenceName = "TAC_LOCATION_SEQ",allocationSize = 1)
	public BigDecimal getLocationId() {
		return this.locationId;
	}

	public void setLocationId(BigDecimal locationId) {
		this.locationId = locationId;
	}

	@Column(name = "LOCATION_NAME", length = 200)
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tacCourseLocation")
	public Set<TacCourseRoom> getTacCourseRooms() {
		return this.tacCourseRooms;
	}

	public void setTacCourseRooms(Set<TacCourseRoom> tacCourseRooms) {
		this.tacCourseRooms = tacCourseRooms;
	}

}
