package qa.gov.customs.training.entity;
// Generated Apr 10, 2019 10:27:46 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TacCourseAttendence generated by hbm2java
 */
@Entity
@Table(name = "TAC_COURSE_ATTENDENCE", schema = "CUST_TAC")
public class TacCourseAttendence implements java.io.Serializable {

	private TacCourseAttendenceId id;
	private TacCourseAttendees tacCourseAttendees;

	public TacCourseAttendence() {
	}

	public TacCourseAttendence(TacCourseAttendenceId id, TacCourseAttendees tacCourseAttendees) {
		this.id = id;
		this.tacCourseAttendees = tacCourseAttendees;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "attendanceId", column = @Column(name = "ATTENDANCE_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "courseDate", column = @Column(name = "COURSE_DATE", length = 7)),
			@AttributeOverride(name = "attendanceFlag", column = @Column(name = "ATTENDANCE_FLAG", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "remark", column = @Column(name = "REMARK")) })
	public TacCourseAttendenceId getId() {
		return this.id;
	}

	public void setId(TacCourseAttendenceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATTENDANCE_ID", nullable = false, insertable = false, updatable = false)
	public TacCourseAttendees getTacCourseAttendees() {
		return this.tacCourseAttendees;
	}

	public void setTacCourseAttendees(TacCourseAttendees tacCourseAttendees) {
		this.tacCourseAttendees = tacCourseAttendees;
	}

}
