package qa.gov.customs.training.entity;
// Generated Apr 10, 2019 10:27:46 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TacCourseAttendees generated by hbm2java
 */
@Entity
@Table(name = "TAC_COURSE_ATTENDEES", schema = "CUST_TAC")
public class TacCourseAttendees implements java.io.Serializable {

	private BigDecimal attendanceId;
	private TacCourseActivation tacCourseActivation;
	private String jobId;
	private String name;
	private String department;
	private String mobile;
	private String jobTitle;
	private BigDecimal courseStatus;
	private BigDecimal attendancePercentage;
	private Clob remark;
	private Set<TacCourseAttendence> tacCourseAttendences = new HashSet<TacCourseAttendence>(0);

	public TacCourseAttendees() {
	}

	public TacCourseAttendees(BigDecimal attendanceId, TacCourseActivation tacCourseActivation, String jobId) {
		this.attendanceId = attendanceId;
		this.tacCourseActivation = tacCourseActivation;
		this.jobId = jobId;
	}

	public TacCourseAttendees(BigDecimal attendanceId, TacCourseActivation tacCourseActivation, String jobId,
			String name, String department, String mobile, String jobTitle, BigDecimal courseStatus,
			BigDecimal attendancePercentage, Clob remark, Set<TacCourseAttendence> tacCourseAttendences) {
		this.attendanceId = attendanceId;
		this.tacCourseActivation = tacCourseActivation;
		this.jobId = jobId;
		this.name = name;
		this.department = department;
		this.mobile = mobile;
		this.jobTitle = jobTitle;
		this.courseStatus = courseStatus;
		this.attendancePercentage = attendancePercentage;
		this.remark = remark;
		this.tacCourseAttendences = tacCourseAttendences;
	}

	@Id

	@Column(name = "ATTENDANCE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAttendanceId() {
		return this.attendanceId;
	}

	public void setAttendanceId(BigDecimal attendanceId) {
		this.attendanceId = attendanceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTIVATION_ID", nullable = false)
	public TacCourseActivation getTacCourseActivation() {
		return this.tacCourseActivation;
	}

	public void setTacCourseActivation(TacCourseActivation tacCourseActivation) {
		this.tacCourseActivation = tacCourseActivation;
	}

	@Column(name = "JOB_ID", nullable = false, length = 20)
	public String getJobId() {
		return this.jobId;
	}

	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	@Column(name = "NAME", length = 500)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DEPARTMENT", length = 500)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "MOBILE", length = 50)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "JOB_TITLE", length = 500)
	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Column(name = "COURSE_STATUS", precision = 22, scale = 0)
	public BigDecimal getCourseStatus() {
		return this.courseStatus;
	}

	public void setCourseStatus(BigDecimal courseStatus) {
		this.courseStatus = courseStatus;
	}

	@Column(name = "ATTENDANCE_PERCENTAGE", precision = 22, scale = 0)
	public BigDecimal getAttendancePercentage() {
		return this.attendancePercentage;
	}

	public void setAttendancePercentage(BigDecimal attendancePercentage) {
		this.attendancePercentage = attendancePercentage;
	}

	@Column(name = "REMARK")
	public Clob getRemark() {
		return this.remark;
	}

	public void setRemark(Clob remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tacCourseAttendees")
	public Set<TacCourseAttendence> getTacCourseAttendences() {
		return this.tacCourseAttendences;
	}

	public void setTacCourseAttendences(Set<TacCourseAttendence> tacCourseAttendences) {
		this.tacCourseAttendences = tacCourseAttendences;
	}

}
