package qa.gov.customs.training.entity;
// Generated Apr 10, 2019 10:27:46 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TacCourseOutcome generated by hbm2java
 */
@Entity
@Table(name = "TAC_COURSE_OUTCOME", schema = "CUST_TAC")
public class TacCourseOutcome implements java.io.Serializable {

	private BigDecimal outcomeId;
	private TacCourseMaster tacCourseMaster;
	private String result;

	public TacCourseOutcome() {
	}

	public TacCourseOutcome(BigDecimal outcomeId) {
		this.outcomeId = outcomeId;
	}

	public TacCourseOutcome(BigDecimal outcomeId, TacCourseMaster tacCourseMaster, String result) {
		this.outcomeId = outcomeId;
		this.tacCourseMaster = tacCourseMaster;
		this.result = result;
	}

	@Id

	@Column(name = "OUTCOME_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getOutcomeId() {
		return this.outcomeId;
	}

	public void setOutcomeId(BigDecimal outcomeId) {
		this.outcomeId = outcomeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COURSE_ID")
	public TacCourseMaster getTacCourseMaster() {
		return this.tacCourseMaster;
	}

	public void setTacCourseMaster(TacCourseMaster tacCourseMaster) {
		this.tacCourseMaster = tacCourseMaster;
	}

	@Column(name = "RESULT", length = 2000)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
