package qa.gov.customs.training.entity;
// Generated Apr 10, 2019 10:27:46 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TacCourseCategory generated by hbm2java
 */
@Entity
@Table(name = "TAC_COURSE_CATEGORY", schema = "CUST_TAC")
public class TacCourseCategory implements java.io.Serializable {

	private BigDecimal categoryId;
	private String description;
	private Set<TacCourseMaster> tacCourseMasters = new HashSet<TacCourseMaster>(0);

	public TacCourseCategory() {
	}

	public TacCourseCategory(BigDecimal categoryId) {
		this.categoryId = categoryId;
	}

	public TacCourseCategory(BigDecimal categoryId, String description, Set<TacCourseMaster> tacCourseMasters) {
		this.categoryId = categoryId;
		this.description = description;
		this.tacCourseMasters = tacCourseMasters;
	}

	@Id

	@Column(name = "CATEGORY_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(BigDecimal categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "DESCRIPTION", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tacCourseCategory")
	public Set<TacCourseMaster> getTacCourseMasters() {
		return this.tacCourseMasters;
	}

	public void setTacCourseMasters(Set<TacCourseMaster> tacCourseMasters) {
		this.tacCourseMasters = tacCourseMasters;
	}

}
