package qa.gov.customs.training.entity;
// Generated Apr 23, 2019 7:33:17 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.math.BigDecimal;

/**
 * TacCommQualifications generated by hbm2java
 */
@Entity
@Table(name = "TAC_COMM_QUALIFICATIONS", schema = "CUST_TAC")
public class TacCommQualifications implements java.io.Serializable {

    private BigDecimal qualificationId;
    private String qualificationName;
//	private Set<TacInstructorQualifications> tacInstructorQualificationses = new HashSet<TacInstructorQualifications>(
//			0);

    public TacCommQualifications() {
    }

    public TacCommQualifications(BigDecimal qualificationId) {
        this.qualificationId = qualificationId;
    }

    public TacCommQualifications(BigDecimal qualificationId, String qualificationName
    ) {
        this.qualificationId = qualificationId;
        this.qualificationName = qualificationName;
        //this.tacInstructorQualificationses = tacInstructorQualificationses;
    }

    @Id

    @Column(name = "QUALIFICATION_ID", unique = true, nullable = false, precision = 22, scale = 0)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_Sequence")
    @SequenceGenerator(name = "id_Sequence", sequenceName = "TAC_QUALIFICATION_SEQ", allocationSize = 1)
    public BigDecimal getQualificationId() {
        return this.qualificationId;
    }

    public void setQualificationId(BigDecimal qualificationId) {
        this.qualificationId = qualificationId;
    }

    @Column(name = "QUALIFICATION_NAME", length = 250)
    public String getQualificationName() {
        return this.qualificationName;
    }

    public void setQualificationName(String qualificationName) {
        this.qualificationName = qualificationName;
    }

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tacCommQualifications")
//	public Set<TacInstructorQualifications> getTacInstructorQualificationses() {
//		return this.tacInstructorQualificationses;
//	}
//
//	public void setTacInstructorQualificationses(Set<TacInstructorQualifications> tacInstructorQualificationses) {
//		this.tacInstructorQualificationses = tacInstructorQualificationses;
//	}

}
