//package qa.gov.customs.training.entity;
//// Generated Apr 23, 2019 7:33:17 AM by Hibernate Tools 4.3.1.Final
//
//import java.math.BigDecimal;
//import java.sql.Clob;
//import java.util.Date;
//import javax.persistence.Column;
//import javax.persistence.Embeddable;
//
///**
// * TacCourseAttendenceId generated by hbm2java
// */
//@Embeddable
//public class TacCourseAttendenceId implements java.io.Serializable {
//
//	private BigDecimal attendanceId;
//	private Date courseDate;
//	private BigDecimal attendanceFlag;
//	private Clob remark;
//
//	public TacCourseAttendenceId() {
//	}
//
//	public TacCourseAttendenceId(BigDecimal attendanceId, BigDecimal attendanceFlag) {
//		this.attendanceId = attendanceId;
//		this.attendanceFlag = attendanceFlag;
//	}
//
//	public TacCourseAttendenceId(BigDecimal attendanceId, Date courseDate, BigDecimal attendanceFlag, Clob remark) {
//		this.attendanceId = attendanceId;
//		this.courseDate = courseDate;
//		this.attendanceFlag = attendanceFlag;
//		this.remark = remark;
//	}
//
//	@Column(name = "ATTENDANCE_ID", nullable = false, precision = 22, scale = 0)
//	public BigDecimal getAttendanceId() {
//		return this.attendanceId;
//	}
//
//	public void setAttendanceId(BigDecimal attendanceId) {
//		this.attendanceId = attendanceId;
//	}
//
//	@Column(name = "COURSE_DATE", length = 7)
//	public Date getCourseDate() {
//		return this.courseDate;
//	}
//
//	public void setCourseDate(Date courseDate) {
//		this.courseDate = courseDate;
//	}
//
//	@Column(name = "ATTENDANCE_FLAG", nullable = false, precision = 22, scale = 0)
//	public BigDecimal getAttendanceFlag() {
//		return this.attendanceFlag;
//	}
//
//	public void setAttendanceFlag(BigDecimal attendanceFlag) {
//		this.attendanceFlag = attendanceFlag;
//	}
//
//	@Column(name = "REMARK")
//	public Clob getRemark() {
//		return this.remark;
//	}
//
//	public void setRemark(Clob remark) {
//		this.remark = remark;
//	}
//
//	public boolean equals(Object other) {
//		if ((this == other))
//			return true;
//		if ((other == null))
//			return false;
//		if (!(other instanceof TacCourseAttendenceId))
//			return false;
//		TacCourseAttendenceId castOther = (TacCourseAttendenceId) other;
//
//		return ((this.getAttendanceId() == castOther.getAttendanceId()) || (this.getAttendanceId() != null
//				&& castOther.getAttendanceId() != null && this.getAttendanceId().equals(castOther.getAttendanceId())))
//				&& ((this.getCourseDate() == castOther.getCourseDate()) || (this.getCourseDate() != null
//						&& castOther.getCourseDate() != null && this.getCourseDate().equals(castOther.getCourseDate())))
//				&& ((this.getAttendanceFlag() == castOther.getAttendanceFlag())
//						|| (this.getAttendanceFlag() != null && castOther.getAttendanceFlag() != null
//								&& this.getAttendanceFlag().equals(castOther.getAttendanceFlag())))
//				&& ((this.getRemark() == castOther.getRemark()) || (this.getRemark() != null
//						&& castOther.getRemark() != null && this.getRemark().equals(castOther.getRemark())));
//	}
//
//	public int hashCode() {
//		int result = 17;
//
//		result = 37 * result + (getAttendanceId() == null ? 0 : this.getAttendanceId().hashCode());
//		result = 37 * result + (getCourseDate() == null ? 0 : this.getCourseDate().hashCode());
//		result = 37 * result + (getAttendanceFlag() == null ? 0 : this.getAttendanceFlag().hashCode());
//		result = 37 * result + (getRemark() == null ? 0 : this.getRemark().hashCode());
//		return result;
//	}
//
//}
