package qa.gov.customs.training.entity;
// Generated Apr 23, 2019 7:33:17 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TacInstructorQualifications generated by hbm2java
 */
@Entity
@Table(name = "TAC_INSTRUCTOR_QUALIFICATIONS", schema = "CUST_TAC")
public class TacInstructorQualifications implements java.io.Serializable {

	private TacInstructorQualificationsId id;
	private TacInstructorMaster tacInstructorMaster;
	private TacCommQualifications tacCommQualifications;

	public TacInstructorQualifications() {
	}

	public TacInstructorQualifications(TacInstructorQualificationsId id, TacInstructorMaster tacInstructorMaster,
			TacCommQualifications tacCommQualifications) {
		this.id = id;
		this.tacInstructorMaster = tacInstructorMaster;
		this.tacCommQualifications = tacCommQualifications;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "instructorId", column = @Column(name = "INSTRUCTOR_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "qualificationId", column = @Column(name = "QUALIFICATION_ID", nullable = false, precision = 22, scale = 0)) })
	public TacInstructorQualificationsId getId() {
		return this.id;
	}

	public void setId(TacInstructorQualificationsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INSTRUCTOR_ID", nullable = false, insertable = false, updatable = false)
	public TacInstructorMaster getTacInstructorMaster() {
		return this.tacInstructorMaster;
	}

	public void setTacInstructorMaster(TacInstructorMaster tacInstructorMaster) {
		this.tacInstructorMaster = tacInstructorMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUALIFICATION_ID", nullable = false, insertable = false, updatable = false)
	public TacCommQualifications getTacCommQualifications() {
		return this.tacCommQualifications;
	}

	public void setTacCommQualifications(TacCommQualifications tacCommQualifications) {
		this.tacCommQualifications = tacCommQualifications;
	}

}
