package qa.gov.customs.training.entity;
// Generated Apr 23, 2019 7:33:17 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TacInstructorSubjectsId generated by hbm2java
 */
@Embeddable
public class TacInstructorSubjectsId implements java.io.Serializable {

	private BigDecimal instructorId;
	private BigDecimal subjectId;

	public TacInstructorSubjectsId() {
	}

	public TacInstructorSubjectsId(BigDecimal instructorId) {
		this.instructorId = instructorId;
	}

	public TacInstructorSubjectsId(BigDecimal instructorId, BigDecimal subjectId) {
		this.instructorId = instructorId;
		this.subjectId = subjectId;
	}

	@Column(name = "INSTRUCTOR_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getInstructorId() {
		return this.instructorId;
	}

	public void setInstructorId(BigDecimal instructorId) {
		this.instructorId = instructorId;
	}

	@Column(name = "SUBJECT_ID", precision = 22, scale = 0)
	public BigDecimal getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(BigDecimal subjectId) {
		this.subjectId = subjectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TacInstructorSubjectsId))
			return false;
		TacInstructorSubjectsId castOther = (TacInstructorSubjectsId) other;

		return ((this.getInstructorId() == castOther.getInstructorId()) || (this.getInstructorId() != null
				&& castOther.getInstructorId() != null && this.getInstructorId().equals(castOther.getInstructorId())))
				&& ((this.getSubjectId() == castOther.getSubjectId()) || (this.getSubjectId() != null
						&& castOther.getSubjectId() != null && this.getSubjectId().equals(castOther.getSubjectId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getInstructorId() == null ? 0 : this.getInstructorId().hashCode());
		result = 37 * result + (getSubjectId() == null ? 0 : this.getSubjectId().hashCode());
		return result;
	}

}
