package qa.gov.customs.training.entity;
// Generated Apr 23, 2019 7:33:17 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TacInstructorSubjects generated by hbm2java
 */
@Entity
@Table(name = "TAC_INSTRUCTOR_SUBJECTS", schema = "CUST_TAC")
public class TacInstructorSubjects implements java.io.Serializable {

	private TacInstructorSubjectsId id;
	private TacInstructorMaster tacInstructorMaster;
	private TacCommSubjects tacCommSubjects;

	public TacInstructorSubjects() {
	}

	public TacInstructorSubjects(TacInstructorSubjectsId id, TacInstructorMaster tacInstructorMaster) {
		this.id = id;
		this.tacInstructorMaster = tacInstructorMaster;
	}

	public TacInstructorSubjects(TacInstructorSubjectsId id, TacInstructorMaster tacInstructorMaster,
			TacCommSubjects tacCommSubjects) {
		this.id = id;
		this.tacInstructorMaster = tacInstructorMaster;
		this.tacCommSubjects = tacCommSubjects;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "instructorId", column = @Column(name = "INSTRUCTOR_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "subjectId", column = @Column(name = "SUBJECT_ID", precision = 22, scale = 0)) })
	public TacInstructorSubjectsId getId() {
		return this.id;
	}

	public void setId(TacInstructorSubjectsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INSTRUCTOR_ID", nullable = false, insertable = false, updatable = false)
	public TacInstructorMaster getTacInstructorMaster() {
		return this.tacInstructorMaster;
	}

	public void setTacInstructorMaster(TacInstructorMaster tacInstructorMaster) {
		this.tacInstructorMaster = tacInstructorMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBJECT_ID", insertable = false, updatable = false)
	public TacCommSubjects getTacCommSubjects() {
		return this.tacCommSubjects;
	}

	public void setTacCommSubjects(TacCommSubjects tacCommSubjects) {
		this.tacCommSubjects = tacCommSubjects;
	}

}
