//package qa.gov.customs.training.entity;
//// Generated Apr 23, 2019 7:33:17 AM by Hibernate Tools 4.3.1.Final
//
//import java.math.BigDecimal;
//import javax.persistence.Column;
//import javax.persistence.Embeddable;
//
///**
// * TacInstructorQualificationsId generated by hbm2java
// */
//@Embeddable
//public class TacInstructorQualificationsId implements java.io.Serializable {
//
//	private BigDecimal instructorId;
//	private BigDecimal qualificationId;
//
//	public TacInstructorQualificationsId() {
//	}
//
//	public TacInstructorQualificationsId(BigDecimal instructorId, BigDecimal qualificationId) {
//		this.instructorId = instructorId;
//		this.qualificationId = qualificationId;
//	}
//
//	@Column(name = "INSTRUCTOR_ID", nullable = false, precision = 22, scale = 0)
//	public BigDecimal getInstructorId() {
//		return this.instructorId;
//	}
//
//	public void setInstructorId(BigDecimal instructorId) {
//		this.instructorId = instructorId;
//	}
//
//	@Column(name = "QUALIFICATION_ID", nullable = false, precision = 22, scale = 0)
//	public BigDecimal getQualificationId() {
//		return this.qualificationId;
//	}
//
//	public void setQualificationId(BigDecimal qualificationId) {
//		this.qualificationId = qualificationId;
//	}
//
//	public boolean equals(Object other) {
//		if ((this == other))
//			return true;
//		if ((other == null))
//			return false;
//		if (!(other instanceof TacInstructorQualificationsId))
//			return false;
//		TacInstructorQualificationsId castOther = (TacInstructorQualificationsId) other;
//
//		return ((this.getInstructorId() == castOther.getInstructorId()) || (this.getInstructorId() != null
//				&& castOther.getInstructorId() != null && this.getInstructorId().equals(castOther.getInstructorId())))
//				&& ((this.getQualificationId() == castOther.getQualificationId())
//						|| (this.getQualificationId() != null && castOther.getQualificationId() != null
//								&& this.getQualificationId().equals(castOther.getQualificationId())));
//	}
//
//	public int hashCode() {
//		int result = 17;
//
//		result = 37 * result + (getInstructorId() == null ? 0 : this.getInstructorId().hashCode());
//		result = 37 * result + (getQualificationId() == null ? 0 : this.getQualificationId().hashCode());
//		return result;
//	}
//
//}
