debug: false
server:
  port: 9000

spring:
  application:
    name: workflow
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: sarath
    password: 12345
    driver-class-name: oracle.jdbc.OracleDriver
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS : false
    time-zone: UTC


logging:
  pattern:
    console: '@%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
    file: '@%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
    qa:
      gov:
        customs:
          workflow: DEBUG
  file: logs/workflow.log

management:
    endpoint:
      flowable:
        enabled: true

