spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true

server:
  port: 9000

feign:
  hystrix:
    enabled: false


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
##service routing setting
#  zuul.ignored-services=*
#  zuul.sensitive-headers=Cookie,Set-Cookie
#  zuul.ignored-headers=Access-Control-Allow-Credentials, Access-Control-Allow-Origin
zuul:
  ignoredServices: '*'
  #ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Authorization,Content-Type
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    connect-timeout-millis: 80000
    socket-timeout-millis: 80000

  routes:
    auth-service:
      sensitiveHeaders:
      path: /authentication/**
      url: http://localhost:9001
      stripPrefix: true

    account-service:
      path: /training/**
      serviceId: training
      stripPrefix: true
      sensitiveHeaders:

    user-service:
      path: /user/**
      serviceId: user
      stripPrefix: true
      sensitiveHeaders:

    file-service:
      path: /fileupload/**
      serviceId: fileupload
      stripPrefix: true
      sensitiveHeaders:

    employee-service:
      path: /employee/**
      serviceId: employee
      stripPrefix: true
      sensitiveHeaders:

    cis-service:
      path: /cis/**
      serviceId: cis
      stripPrefix: true
      sensitiveHeaders:



debug: true

logging:
  pattern:
    console: '@%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
    file: '@%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
    qa:
      gov:
        customs:
          gateway: DEBUG
  file: logs/gateway.log


