spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true

server:
  port: 9000

#feign:
#  hystrix:
#    enabled: false

#hystrix.command.default.execution.timeout.enabled: false

#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false
#        isolation:
#          thread:
#            timeoutInMilliseconds: 30000
#(5000 * 60000) *  (1 + 0) * (2 + 1) = xxxx ms
#eg:


#    ribbon.connectionTimeout is 5000
#    ribbon.readTimeout is 15000
#    ribbon.maxAutoRetries is 0 (default)
#    ribbon.maxAutoRetriesNextServer is 1 (default)

#So the hystrixTimeout should be:

#  (5000 + 15000) * (1 + 0) * (1 + 1) // -> 40000 ms



# If you choose to not configure Hystrix timeout, the default Hystrix timeout will be xxxx ms .
#(ribbon.ConnectTimeout + ribbon.ReadTimeout) * (ribbon.MaxAutoRetries + 1) * (ribbon.MaxAutoRetriesNextServer + 1)
# https://cloud.spring.io/spring-cloud-static/Edgware.SR3/single/spring-cloud.html#_zuul_timeouts
# load ribbon on startup
#ribbon:
#  ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  eureka:
    enabled: true
#ribbon:
#  ReadTimeout: 100000
#  ConnectTimeout: 10000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1
#  eureka:
#    enabled: true
#  eager-load:
#    enabled: true

##service routing setting
#  zuul.ignored-services=*
#  zuul.sensitive-headers=Cookie,Set-Cookie
#  zuul.ignored-headers=Access-Control-Allow-Credentials, Access-Control-Allow-Origin
#zuul.RibbonRoutingFilter.route.disable=true
zuul:
  ignoredServices: '*'
  #ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Authorization,Content-Type
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
#  host:
#    connect-timeout-millis: 60000
#    socket-timeout-millis: 60000
  routes:
    auth-service:
      sensitiveHeaders:
      path: /authentication/**
      url: ${LOGIN_SERVER_URL:http://localhost:9001}
      stripPrefix: true

    training:
      path: /training/**
      serviceId: training
      stripPrefix: true
      sensitiveHeaders:

    user:
      path: /user/**
      serviceId: user
      stripPrefix: true
      sensitiveHeaders:

    fileupload:
      path: /fileupload/**
      serviceId: fileupload
      stripPrefix: true
      sensitiveHeaders:

    employee:
      path: /employee/**
      serviceId: employee
      stripPrefix: true
      sensitiveHeaders:

    cis:
      path: /cis/**
      serviceId: cis
      stripPrefix: true
      sensitiveHeaders:



#debug: true

logging:
  pattern:
    console: '@%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
    file: '@%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
    qa:
      gov:
        customs:
          gateway: DEBUG
  file: logs/gateway.log

#eureka:
#  client:
#    fetchRegistry: true
#    registryFetchIntervalSeconds: 5
#    serviceUrl:
#      defaultZone: http://${REGISTRY_URL:registry}:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    hostname: gateway
eureka:
  client:
    healthcheck: true
    leaseRenewalIntervalInSeconds: 10
    #registryFetchIntervalSeconds: 5
    #fetch-registry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://${REGISTRY_URL:registry}:8761}/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true

# http://${REGISTRY_URL:registry}:8761/eureka/

cloud:
  inetutils:
    prfered-networks:
      - 10.0

#training:
#  ribbon:
#    eureka:
#      enabled: false
#    #NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#    ConnectTimeout: 15000
#    ReadTimeout: 15000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100
#
#user:
#  ribbon:
#    eureka:
#      enabled: true
#    #NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#    ConnectTimeout: 15000
#    ReadTimeout: 15000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100
#
#fileupload:
#  ribbon:
#    eureka:
#      enabled: true
#    #NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#    ConnectTimeout: 15000
#    ReadTimeout: 15000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100
#
#employee:
#  ribbon:
#    eureka:
#      enabled: true
#    #NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#    ConnectTimeout: 15000
#    ReadTimeout: 15000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100
#
#auth-service:
#  ribbon:
#    eureka:
#      enabled: true
#    #NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#    ConnectTimeout: 15000
#    ReadTimeout: 15000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100
#management:
#  health:
#    elasticsearch:
#      response-timeout:
