spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true

server:
  port: 9000

feign:
  hystrix:
    enabled: false


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /authentication/**
      url: http://localhost:9001
      stripPrefix: false
      sensitiveHeaders:

    account-service:
      path: /training/**
      serviceId: training
      stripPrefix: false
      sensitiveHeaders:





