spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true

server:
  port: 9000

#feign:
#  hystrix:
#    enabled: false



#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 15000
#(5000 * 60000) *  (1 + 0) * (2 + 1) = xxxx ms
# If you choose to not configure Hystrix timeout, the default Hystrix timeout will be xxxx ms .
#(ribbon.ConnectTimeout + ribbon.ReadTimeout) * (ribbon.MaxAutoRetries + 1) * (ribbon.MaxAutoRetriesNextServer + 1)
# https://cloud.spring.io/spring-cloud-static/Edgware.SR3/single/spring-cloud.html#_zuul_timeouts
# load ribbon on startup
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 60000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 0
  eager-load:
    enabled: true
##service routing setting
#  zuul.ignored-services=*
#  zuul.sensitive-headers=Cookie,Set-Cookie
#  zuul.ignored-headers=Access-Control-Allow-Credentials, Access-Control-Allow-Origin
zuul:
  ignoredServices: '*'
  #ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Authorization,Content-Type
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  #host:
  #  connect-timeout-millis: 60000
  #  socket-timeout-millis: 60000

  routes:
    auth-service:
      sensitiveHeaders:
      path: /authentication/**
      url: ${LOGIN_SERVER_URL:http://localhost:9001}
      stripPrefix: true

    training:
      path: /training/**
      serviceId: training
      stripPrefix: true
      sensitiveHeaders:

    user:
      path: /user/**
      serviceId: user
      stripPrefix: true
      sensitiveHeaders:

    fileupload:
      path: /fileupload/**
      serviceId: fileupload
      stripPrefix: true
      sensitiveHeaders:

    employee:
      path: /employee/**
      serviceId: employee
      stripPrefix: true
      sensitiveHeaders:

    cis:
      path: /cis/**
      serviceId: cis
      stripPrefix: true
      sensitiveHeaders:



debug: true

logging:
  pattern:
    console: '@%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
    file: '@%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
    qa:
      gov:
        customs:
          gateway: DEBUG
  file: logs/gateway.log

#eureka:
#  client:
#    fetchRegistry: true
#    registryFetchIntervalSeconds: 5
#    serviceUrl:
#      defaultZone: http://${REGISTRY_URL:registry}:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    hostname: gateway
eureka:
  client:
    healthcheck: true
    registryFetchIntervalSeconds: 5
    fetch-registry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://${REGISTRY_URL:localhost}:8761}/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true

# http://${REGISTRY_URL:registry}:8761/eureka/

#cloud:
#  inetutils:
#    prfered-networks:
#      - 10.0

#training:
#  ribbon:
#    eureka:
#      enabled: true
#    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#    ConnectTimeout: 5000
#    ReadTimeout: 5000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100
#
#user:
#  ribbon:
#    eureka:
#      enabled: true
#    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#    ConnectTimeout: 5000
#    ReadTimeout: 5000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100
#
#fileupload:
#  ribbon:
#    eureka:
#      enabled: true
#    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#    ConnectTimeout: 5000
#    ReadTimeout: 5000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100
#
#employee:
#  ribbon:
#    eureka:
#      enabled: true
#    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#    ConnectTimeout: 5000
#    ReadTimeout: 5000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100
#
#auth-service:
#  ribbon:
#    eureka:
#      enabled: true
#    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#    ConnectTimeout: 5000
#    ReadTimeout: 5000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100

