#security:
#  oauth2:
#    resource:
#      jwt:
#        key-value:
#          -----BEGIN PUBLIC KEY-----
#          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnXaDQtFEcmUVf2DlcCi1
#          V8uPfDT54Z5RG1afpqbAgvor0V3SopLuKEBm8DUGwLume31k9GtUWnm9BjlIWDvK
#          Zogn22YyKWWeHVfy+1SHL3owtR4iaS43pVQTEuIBcGC//vCRd8aWByqv0U6zVWoe
#          ejG9MiDjyQztUuqi1wJQeDr6Th0m+kAWw7Xk44kd7vp+ZnzAsDJC4S5eS1Dbm8qx
#          xHe8C7HxuJAKvafxMjXZmIhocaCSHk/VroDOJYC+a7vl+gNY+qnM1Wr5CYNNkUKw
#          mQcrvWJogMeo05eegZBUF//Yhsv4FLDZO0HIvwB3qSKUWwzv4RF922jOYp/3f6Oi
#          YwIDAQAB
#          -----END PUBLIC KEY-----
#    client:
#      clientId: registry
      #clientSecret: password@2018
      #accessTokenUri: http://localhost:9001/oauth/token
      #grant-type: client_credentials
      #scope: server

spring:
  application:
    name: registry
  main:
    allow-bean-definition-overriding: true

server:
  port: 8761

feign:
  hystrix:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

logging:
  pattern:
    console: '@%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
    file: '@%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
    qa:
      gov:
        customs:
          authentication: DEBUG
  file: logs/registry.log

management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
    web:
      exposure:
        include: ["health","routes","metrics","info"]
      enabled: true