package qa.gov.customs.employee.entity;
// Generated Apr 23, 2019 12:58:10 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * EmpEducationLevel generated by hbm2java
 */
@Entity
@Table(name = "EMP_EDUCATION_LEVEL", schema = "CUST_EMPLOYEE")
public class EmpEducationLevel implements java.io.Serializable {

    private BigDecimal educationLevelCode;
    private String educationLevelDescEn;
    private String educationLevelDescAr;
    private Set<EmpSelfstudyMaster> empSelfstudyMasters = new HashSet<EmpSelfstudyMaster>(0);

    public EmpEducationLevel() {
    }

    public EmpEducationLevel(BigDecimal educationLevelCode) {
        this.educationLevelCode = educationLevelCode;
    }

    public EmpEducationLevel(BigDecimal educationLevelCode, String educationLevelDescEn, String educationLevelDescAr,
                             Set<EmpSelfstudyMaster> empSelfstudyMasters) {
        this.educationLevelCode = educationLevelCode;
        this.educationLevelDescEn = educationLevelDescEn;
        this.educationLevelDescAr = educationLevelDescAr;
        this.empSelfstudyMasters = empSelfstudyMasters;
    }

    @Id

    @Column(name = "EDUCATION_LEVEL_CODE", unique = true, nullable = false, precision = 22, scale = 0)

    public BigDecimal getEducationLevelCode() {
        return this.educationLevelCode;
    }

    public void setEducationLevelCode(BigDecimal educationLevelCode) {
        this.educationLevelCode = educationLevelCode;
    }

    @Column(name = "EDUCATION_LEVEL_DESC_EN", length = 200)
    public String getEducationLevelDescEn() {
        return this.educationLevelDescEn;
    }

    public void setEducationLevelDescEn(String educationLevelDescEn) {
        this.educationLevelDescEn = educationLevelDescEn;
    }

    @Column(name = "EDUCATION_LEVEL_DESC_AR", length = 200)
    public String getEducationLevelDescAr() {
        return this.educationLevelDescAr;
    }

    public void setEducationLevelDescAr(String educationLevelDescAr) {
        this.educationLevelDescAr = educationLevelDescAr;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empEducationLevel")
    public Set<EmpSelfstudyMaster> getEmpSelfstudyMasters() {
        return this.empSelfstudyMasters;
    }

    public void setEmpSelfstudyMasters(Set<EmpSelfstudyMaster> empSelfstudyMasters) {
        this.empSelfstudyMasters = empSelfstudyMasters;
    }

}
