package qa.gov.customs.employee.entity;
// Generated Apr 23, 2019 12:58:10 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpEmployeeMasterId generated by hbm2java
 */
@Embeddable
public class EmpEmployeeMasterId implements java.io.Serializable {

	private String jobId;
	private BigDecimal verNo;

	public EmpEmployeeMasterId() {
	}

	public EmpEmployeeMasterId(String jobId, BigDecimal verNo) {
		this.jobId = jobId;
		this.verNo = verNo;
	}

	@Column(name = "JOB_ID", nullable = false, length = 20)
	public String getJobId() {
		return this.jobId;
	}

	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	@Column(name = "VER_NO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getVerNo() {
		return this.verNo;
	}

	public void setVerNo(BigDecimal verNo) {
		this.verNo = verNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmpEmployeeMasterId))
			return false;
		EmpEmployeeMasterId castOther = (EmpEmployeeMasterId) other;

		return ((this.getJobId() == castOther.getJobId()) || (this.getJobId() != null && castOther.getJobId() != null
				&& this.getJobId().equals(castOther.getJobId())))
				&& ((this.getVerNo() == castOther.getVerNo()) || (this.getVerNo() != null
						&& castOther.getVerNo() != null && this.getVerNo().equals(castOther.getVerNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getJobId() == null ? 0 : this.getJobId().hashCode());
		result = 37 * result + (getVerNo() == null ? 0 : this.getVerNo().hashCode());
		return result;
	}

}
