package qa.gov.customs.employee.entity;
// Generated Apr 23, 2019 12:58:10 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmpGroup generated by hbm2java
 */
@Entity
@Table(name = "EMP_GROUP", schema = "CUST_EMPLOYEE")
public class EmpGroup implements java.io.Serializable {

	private String empGroupCode;
	private String empGroupDescEn;
	private String empGroupDescAr;
	private Set<EmpEmployeeMaster> empEmployeeMasters = new HashSet<EmpEmployeeMaster>(0);

	public EmpGroup() {
	}

	public EmpGroup(String empGroupCode) {
		this.empGroupCode = empGroupCode;
	}

	public EmpGroup(String empGroupCode, String empGroupDescEn, String empGroupDescAr,
			Set<EmpEmployeeMaster> empEmployeeMasters) {
		this.empGroupCode = empGroupCode;
		this.empGroupDescEn = empGroupDescEn;
		this.empGroupDescAr = empGroupDescAr;
		this.empEmployeeMasters = empEmployeeMasters;
	}

	@Id

	@Column(name = "EMP_GROUP_CODE", unique = true, nullable = false, length = 20)
	public String getEmpGroupCode() {
		return this.empGroupCode;
	}

	public void setEmpGroupCode(String empGroupCode) {
		this.empGroupCode = empGroupCode;
	}

	@Column(name = "EMP_GROUP_DESC_EN", length = 200)
	public String getEmpGroupDescEn() {
		return this.empGroupDescEn;
	}

	public void setEmpGroupDescEn(String empGroupDescEn) {
		this.empGroupDescEn = empGroupDescEn;
	}

	@Column(name = "EMP_GROUP_DESC_AR", length = 200)
	public String getEmpGroupDescAr() {
		return this.empGroupDescAr;
	}

	public void setEmpGroupDescAr(String empGroupDescAr) {
		this.empGroupDescAr = empGroupDescAr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empGroup")
	public Set<EmpEmployeeMaster> getEmpEmployeeMasters() {
		return this.empEmployeeMasters;
	}

	public void setEmpEmployeeMasters(Set<EmpEmployeeMaster> empEmployeeMasters) {
		this.empEmployeeMasters = empEmployeeMasters;
	}

}
