package qa.gov.customs.employee.entity;
// Generated Apr 23, 2019 12:58:10 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmpJob generated by hbm2java
 */
@Entity
@Table(name = "EMP_JOB", schema = "CUST_EMPLOYEE")
public class EmpJob implements java.io.Serializable {

	private String jobCode;
	private String jobDescEn;
	private String jobDescAr;
	private Set<EmpEmployeeMaster> empEmployeeMasters = new HashSet<EmpEmployeeMaster>(0);

	public EmpJob() {
	}

	public EmpJob(String jobCode) {
		this.jobCode = jobCode;
	}

	public EmpJob(String jobCode, String jobDescEn, String jobDescAr, Set<EmpEmployeeMaster> empEmployeeMasters) {
		this.jobCode = jobCode;
		this.jobDescEn = jobDescEn;
		this.jobDescAr = jobDescAr;
		this.empEmployeeMasters = empEmployeeMasters;
	}

	@Id

	@Column(name = "JOB_CODE", unique = true, nullable = false, length = 20)
	public String getJobCode() {
		return this.jobCode;
	}

	public void setJobCode(String jobCode) {
		this.jobCode = jobCode;
	}

	@Column(name = "JOB_DESC_EN", length = 200)
	public String getJobDescEn() {
		return this.jobDescEn;
	}

	public void setJobDescEn(String jobDescEn) {
		this.jobDescEn = jobDescEn;
	}

	@Column(name = "JOB_DESC_AR", length = 200)
	public String getJobDescAr() {
		return this.jobDescAr;
	}

	public void setJobDescAr(String jobDescAr) {
		this.jobDescAr = jobDescAr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empJob")
	public Set<EmpEmployeeMaster> getEmpEmployeeMasters() {
		return this.empEmployeeMasters;
	}

	public void setEmpEmployeeMasters(Set<EmpEmployeeMaster> empEmployeeMasters) {
		this.empEmployeeMasters = empEmployeeMasters;
	}

}
