package qa.gov.customs.employee.entity;
// Generated Apr 23, 2019 12:58:10 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmpMajor generated by hbm2java
 */
@Entity
@Table(name = "EMP_MAJOR", schema = "CUST_EMPLOYEE")
public class EmpMajor implements java.io.Serializable {

	private BigDecimal majorCode;
	private String majorDescAr;
	private String majorDescEn;
	private Set<EmpSelfstudyMaster> empSelfstudyMasters = new HashSet<EmpSelfstudyMaster>(0);

	public EmpMajor() {
	}

	public EmpMajor(BigDecimal majorCode) {
		this.majorCode = majorCode;
	}

	public EmpMajor(BigDecimal majorCode, String majorDescAr, String majorDescEn,
			Set<EmpSelfstudyMaster> empSelfstudyMasters) {
		this.majorCode = majorCode;
		this.majorDescAr = majorDescAr;
		this.majorDescEn = majorDescEn;
		this.empSelfstudyMasters = empSelfstudyMasters;
	}

	@Id

	@Column(name = "MAJOR_CODE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getMajorCode() {
		return this.majorCode;
	}

	public void setMajorCode(BigDecimal majorCode) {
		this.majorCode = majorCode;
	}

	@Column(name = "MAJOR_DESC_AR", length = 200)
	public String getMajorDescAr() {
		return this.majorDescAr;
	}

	public void setMajorDescAr(String majorDescAr) {
		this.majorDescAr = majorDescAr;
	}

	@Column(name = "MAJOR_DESC_EN", length = 200)
	public String getMajorDescEn() {
		return this.majorDescEn;
	}

	public void setMajorDescEn(String majorDescEn) {
		this.majorDescEn = majorDescEn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empMajor")
	public Set<EmpSelfstudyMaster> getEmpSelfstudyMasters() {
		return this.empSelfstudyMasters;
	}

	public void setEmpSelfstudyMasters(Set<EmpSelfstudyMaster> empSelfstudyMasters) {
		this.empSelfstudyMasters = empSelfstudyMasters;
	}

}
