package qa.gov.customs.employee.entity;
// Generated Apr 23, 2019 12:58:10 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * EmpNationality generated by hbm2java
 */
@Entity
@Table(name = "EMP_NATIONALITY", schema = "CUST_EMPLOYEE")
public class EmpNationality implements java.io.Serializable {

    private String nationalityCode;
    private String nationalityDescEn;
    private String nationalityDescAr;
    private Set<EmpEmployeeMaster> empEmployeeMasters = new HashSet<EmpEmployeeMaster>(0);

    public EmpNationality() {
    }

    public EmpNationality(String nationalityCode) {
        this.nationalityCode = nationalityCode;
    }

    public EmpNationality(String nationalityCode, String nationalityDescEn, String nationalityDescAr,
                          Set<EmpEmployeeMaster> empEmployeeMasters) {
        this.nationalityCode = nationalityCode;
        this.nationalityDescEn = nationalityDescEn;
        this.nationalityDescAr = nationalityDescAr;
        this.empEmployeeMasters = empEmployeeMasters;
    }

    @Id

    @Column(name = "NATIONALITY_CODE", unique = true, nullable = false, length = 20)
    public String getNationalityCode() {
        return this.nationalityCode;
    }

    public void setNationalityCode(String nationalityCode) {
        this.nationalityCode = nationalityCode;
    }

    @Column(name = "NATIONALITY_DESC_EN", length = 200)
    public String getNationalityDescEn() {
        return this.nationalityDescEn;
    }

    public void setNationalityDescEn(String nationalityDescEn) {
        this.nationalityDescEn = nationalityDescEn;
    }

    @Column(name = "NATIONALITY_DESC_AR", length = 200)
    public String getNationalityDescAr() {
        return this.nationalityDescAr;
    }

    public void setNationalityDescAr(String nationalityDescAr) {
        this.nationalityDescAr = nationalityDescAr;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empNationality")
    public Set<EmpEmployeeMaster> getEmpEmployeeMasters() {
        return this.empEmployeeMasters;
    }

    public void setEmpEmployeeMasters(Set<EmpEmployeeMaster> empEmployeeMasters) {
        this.empEmployeeMasters = empEmployeeMasters;
    }

}
