package qa.gov.customs.employee.entity;

//package qa.gov.customs.employee.entity;
//// Generated Apr 23, 2019 12:58:10 PM by Hibernate Tools 4.3.1.Final
//

import javax.persistence.*;
import java.math.BigDecimal;
import java.sql.Date;

//
///**
// * EmpSelfstudyDetails generated by hbm2java
// */
@Entity
@Table(name = "EMP_SELFSTUDY_DETAILS", schema = "CUST_EMPLOYEE")
public class EmpSelfstudyDetails implements java.io.Serializable {

    private BigDecimal SRL_NO;
    private String SUBJECT_NAME;
    private BigDecimal NO_OF_HOURS;
    private Date END_DATE;
    private String EVALUATION;
    private String GRADE;
    private BigDecimal REMAINING_HOURS;
    private String REMARKS;
    private EmpSelfstudyMaster empSelfstudyMaster;
    private BigDecimal DETAILS_SRL_NO;


    public EmpSelfstudyDetails(BigDecimal srlNo, String subjectName, BigDecimal noOfHours, Date endDate,
                               String evaluation, String grade, BigDecimal remainingHours, String remarks, BigDecimal detailsSrlNo) {
        this.SRL_NO = srlNo;
        this.SUBJECT_NAME = subjectName;
        this.NO_OF_HOURS = noOfHours;
        this.END_DATE = endDate;
        this.EVALUATION = evaluation;
        this.GRADE = grade;
        this.REMAINING_HOURS = remainingHours;
        this.REMARKS = remarks;
    }


    @Id

    @Column(name = "DETAILS_SRL_NO", unique = true, nullable = false, precision = 22, scale = 0)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "Id_Sequence")
    @SequenceGenerator(name = "Id_Sequence", sequenceName = "EMP_SELFSTUDYDETAILS_ID_SEQ", allocationSize = 1)
    public BigDecimal getDETAILS_SRL_NO() {
        return DETAILS_SRL_NO;
    }

    public void setDETAILS_SRL_NO(BigDecimal dETAILS_SRL_NO) {
        DETAILS_SRL_NO = dETAILS_SRL_NO;
    }

    public BigDecimal getSRL_NO() {
        return SRL_NO;
    }

    public void setSRL_NO(BigDecimal sRL_NO) {
        SRL_NO = sRL_NO;
    }

    public String getSUBJECT_NAME() {
        return SUBJECT_NAME;
    }

    public void setSUBJECT_NAME(String sUBJECT_NAME) {
        SUBJECT_NAME = sUBJECT_NAME;
    }

    public BigDecimal getNO_OF_HOURS() {
        return NO_OF_HOURS;
    }

    public void setNO_OF_HOURS(BigDecimal nO_OF_HOURS) {
        NO_OF_HOURS = nO_OF_HOURS;
    }

    public Date getEND_DATE() {
        return END_DATE;
    }

    public void setEND_DATE(Date eND_DATE) {
        END_DATE = eND_DATE;
    }

    public String getEVALUATION() {
        return EVALUATION;
    }

    public void setEVALUATION(String eVALUATION) {
        EVALUATION = eVALUATION;
    }

    public String getGRADE() {
        return GRADE;
    }

    public void setGRADE(String gRADE) {
        GRADE = gRADE;
    }

    public BigDecimal getREMAINING_HOURS() {
        return REMAINING_HOURS;
    }

    public void setREMAINING_HOURS(BigDecimal rEMAINING_HOURS) {
        REMAINING_HOURS = rEMAINING_HOURS;
    }

    public String getREMARKS() {
        return REMARKS;
    }

    public void setREMARKS(String rEMARKS) {
        REMARKS = rEMARKS;
    }

    public EmpSelfstudyMaster getEmpSelfstudyMaster() {
        return empSelfstudyMaster;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SRL_NO", nullable = false, insertable = false, updatable = false)
    public void setEmpSelfstudyMaster(EmpSelfstudyMaster empSelfstudyMaster) {
        this.empSelfstudyMaster = empSelfstudyMaster;
    }


}
//	private EmpSelfstudyDetailsId id;
//	private EmpSelfstudyMaster empSelfstudyMaster;
//
//	public EmpSelfstudyDetails() {
//	}
//
//	public EmpSelfstudyDetails(EmpSelfstudyDetailsId id, EmpSelfstudyMaster empSelfstudyMaster) {
//		this.id = id;
//		this.empSelfstudyMaster = empSelfstudyMaster;
//	}
//
//	@EmbeddedId
//
//	@AttributeOverrides({
//			@AttributeOverride(name = "srlNo", column = @Column(name = "SRL_NO", nullable = false, precision = 22, scale = 0)),
//			@AttributeOverride(name = "subjectName", column = @Column(name = "SUBJECT_NAME", length = 200)),
//			@AttributeOverride(name = "noOfHours", column = @Column(name = "NO_OF_HOURS", precision = 22, scale = 0)),
//			@AttributeOverride(name = "endDate", column = @Column(name = "END_DATE", length = 7)),
//			@AttributeOverride(name = "evaluation", column = @Column(name = "EVALUATION", length = 200)),
//			@AttributeOverride(name = "grade", column = @Column(name = "GRADE", length = 200)),
//			@AttributeOverride(name = "remainingHours", column = @Column(name = "REMAINING_HOURS", precision = 22, scale = 0)),
//			@AttributeOverride(name = "remarks", column = @Column(name = "REMARKS", length = 20)) })
//	public EmpSelfstudyDetailsId getId() {
//		return this.id;
//	}
//
//	public void setId(EmpSelfstudyDetailsId id) {
//		this.id = id;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "SRL_NO", nullable = false, insertable = false, updatable = false)
//	public EmpSelfstudyMaster getEmpSelfstudyMaster() {
//		return this.empSelfstudyMaster;
//	}
//
//	public void setEmpSelfstudyMaster(EmpSelfstudyMaster empSelfstudyMaster) {
//		this.empSelfstudyMaster = empSelfstudyMaster;
//	}
//
//}
