package qa.gov.customs.employee.entity;
// Generated Apr 23, 2019 12:58:10 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpSelfstudyMaster generated by hbm2java
 */
@Entity
@Table(name = "EMP_SELFSTUDY_MASTER", schema = "CUST_EMPLOYEE")
public class EmpSelfstudyMaster implements java.io.Serializable {

	private BigDecimal srlNo;
	private EmpUniverstity empUniverstity;
	private EmpMajor empMajor;
	private EmpEducationLevel empEducationLevel;
	private String jobId;
	private Date approvalDate;
	private String letterNo;
	private String evaluation;
	private BigDecimal remainingHours;
	private Clob remarks;
	private String conductCertificate;
	private String status;
	private Set<EmpSelfstudyDetails> empSelfstudyDetailses = new HashSet<EmpSelfstudyDetails>(0);

	public EmpSelfstudyMaster() {
	}

	public EmpSelfstudyMaster(BigDecimal srlNo) {
		this.srlNo = srlNo;
	}

	public EmpSelfstudyMaster(BigDecimal srlNo, EmpUniverstity empUniverstity, EmpMajor empMajor,
			EmpEducationLevel empEducationLevel, String jobId, Date approvalDate, String letterNo, String evaluation,
			BigDecimal remainingHours, Clob remarks, String conductCertificate, String status,
			Set<EmpSelfstudyDetails> empSelfstudyDetailses) {
		this.srlNo = srlNo;
		this.empUniverstity = empUniverstity;
		this.empMajor = empMajor;
		this.empEducationLevel = empEducationLevel;
		this.jobId = jobId;
		this.approvalDate = approvalDate;
		this.letterNo = letterNo;
		this.evaluation = evaluation;
		this.remainingHours = remainingHours;
		this.remarks = remarks;
		this.conductCertificate = conductCertificate;
		this.status = status;
		this.empSelfstudyDetailses = empSelfstudyDetailses;
	}

	@Id

	@Column(name = "SRL_NO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSrlNo() {
		return this.srlNo;
	}

	public void setSrlNo(BigDecimal srlNo) {
		this.srlNo = srlNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNIVERSITY_CODE")
	public EmpUniverstity getEmpUniverstity() {
		return this.empUniverstity;
	}

	public void setEmpUniverstity(EmpUniverstity empUniverstity) {
		this.empUniverstity = empUniverstity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOJOR_CODE")
	public EmpMajor getEmpMajor() {
		return this.empMajor;
	}

	public void setEmpMajor(EmpMajor empMajor) {
		this.empMajor = empMajor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EDUCATION_LEVEL_CODE")
	public EmpEducationLevel getEmpEducationLevel() {
		return this.empEducationLevel;
	}

	public void setEmpEducationLevel(EmpEducationLevel empEducationLevel) {
		this.empEducationLevel = empEducationLevel;
	}

	@Column(name = "JOB_ID", length = 20)
	public String getJobId() {
		return this.jobId;
	}

	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APPROVAL_DATE", length = 7)
	public Date getApprovalDate() {
		return this.approvalDate;
	}

	public void setApprovalDate(Date approvalDate) {
		this.approvalDate = approvalDate;
	}

	@Column(name = "LETTER_NO", length = 20)
	public String getLetterNo() {
		return this.letterNo;
	}

	public void setLetterNo(String letterNo) {
		this.letterNo = letterNo;
	}

	@Column(name = "EVALUATION", length = 20)
	public String getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(String evaluation) {
		this.evaluation = evaluation;
	}

	@Column(name = "REMAINING_HOURS", precision = 22, scale = 0)
	public BigDecimal getRemainingHours() {
		return this.remainingHours;
	}

	public void setRemainingHours(BigDecimal remainingHours) {
		this.remainingHours = remainingHours;
	}

	@Column(name = "REMARKS")
	public Clob getRemarks() {
		return this.remarks;
	}

	public void setRemarks(Clob remarks) {
		this.remarks = remarks;
	}

	@Column(name = "CONDUCT_CERTIFICATE", length = 200)
	public String getConductCertificate() {
		return this.conductCertificate;
	}

	public void setConductCertificate(String conductCertificate) {
		this.conductCertificate = conductCertificate;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empSelfstudyMaster")
	public Set<EmpSelfstudyDetails> getEmpSelfstudyDetailses() {
		return this.empSelfstudyDetailses;
	}

	public void setEmpSelfstudyDetailses(Set<EmpSelfstudyDetails> empSelfstudyDetailses) {
		this.empSelfstudyDetailses = empSelfstudyDetailses;
	}

}
