package qa.gov.customs.employee.entity;
// Generated Apr 23, 2019 12:58:10 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmpSelfstudyDetails generated by hbm2java
 */
@Entity
@Table(name = "EMP_SELFSTUDY_DETAILS", schema = "CUST_EMPLOYEE")
public class EmpSelfstudyDetails implements java.io.Serializable {

	private EmpSelfstudyDetailsId id;
	private EmpSelfstudyMaster empSelfstudyMaster;

	public EmpSelfstudyDetails() {
	}

	public EmpSelfstudyDetails(EmpSelfstudyDetailsId id, EmpSelfstudyMaster empSelfstudyMaster) {
		this.id = id;
		this.empSelfstudyMaster = empSelfstudyMaster;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "srlNo", column = @Column(name = "SRL_NO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "subjectName", column = @Column(name = "SUBJECT_NAME", length = 200)),
			@AttributeOverride(name = "noOfHours", column = @Column(name = "NO_OF_HOURS", precision = 22, scale = 0)),
			@AttributeOverride(name = "endDate", column = @Column(name = "END_DATE", length = 7)),
			@AttributeOverride(name = "evaluation", column = @Column(name = "EVALUATION", length = 200)),
			@AttributeOverride(name = "grade", column = @Column(name = "GRADE", length = 200)),
			@AttributeOverride(name = "remainingHours", column = @Column(name = "REMAINING_HOURS", precision = 22, scale = 0)),
			@AttributeOverride(name = "remarks", column = @Column(name = "REMARKS", length = 20)) })
	public EmpSelfstudyDetailsId getId() {
		return this.id;
	}

	public void setId(EmpSelfstudyDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SRL_NO", nullable = false, insertable = false, updatable = false)
	public EmpSelfstudyMaster getEmpSelfstudyMaster() {
		return this.empSelfstudyMaster;
	}

	public void setEmpSelfstudyMaster(EmpSelfstudyMaster empSelfstudyMaster) {
		this.empSelfstudyMaster = empSelfstudyMaster;
	}

}
