package qa.gov.customs.employee.entity;
// Generated Apr 23, 2019 12:58:10 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * EmpUniverstity generated by hbm2java
 */
@Entity
@Table(name = "EMP_UNIVERSTITY", schema = "CUST_EMPLOYEE")
public class EmpUniverstity implements java.io.Serializable {

    private BigDecimal universityCode;
    private String universityNameEn;
    private String universityNameAr;
    private Set<EmpSelfstudyMaster> empSelfstudyMasters = new HashSet<EmpSelfstudyMaster>(0);

    public EmpUniverstity() {
    }

    public EmpUniverstity(BigDecimal universityCode) {
        this.universityCode = universityCode;
    }

    public EmpUniverstity(BigDecimal universityCode, String universityNameEn, String eniversityNameAr,
                          Set<EmpSelfstudyMaster> empSelfstudyMasters) {
        this.universityCode = universityCode;
        this.universityNameEn = universityNameEn;
        this.universityNameAr = eniversityNameAr;
        this.empSelfstudyMasters = empSelfstudyMasters;
    }

    @Id

    @Column(name = "UNIVERSITY_CODE", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getUniversityCode() {
        return this.universityCode;
    }

    public void setUniversityCode(BigDecimal universityCode) {
        this.universityCode = universityCode;
    }

    @Column(name = "UNIVERSITY_NAME_EN", length = 200)
    public String getUniversityNameEn() {
        return this.universityNameEn;
    }

    public void setUniversityNameEn(String universityNameEn) {
        this.universityNameEn = universityNameEn;
    }

    @Column(name = "ENIVERSITY_NAME_AR", length = 200)
    public String getUniversityNameAr() {
        return this.universityNameAr;
    }

    public void setUniversityNameAr(String eniversityNameAr) {
        this.universityNameAr = eniversityNameAr;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empUniverstity")
    public Set<EmpSelfstudyMaster> getEmpSelfstudyMasters() {
        return this.empSelfstudyMasters;
    }

    public void setEmpSelfstudyMasters(Set<EmpSelfstudyMaster> empSelfstudyMasters) {
        this.empSelfstudyMasters = empSelfstudyMasters;
    }

}
